Repository retaildevcrews/webvalidate, pull requests merged in 2020-04, with the labels that each got.

#48 Updated command line / env vars
  src/app/Constants.cs
  src/app/Program.cs
  src/app/TestFiles/bad.json
  src/app/TestFiles/baseline.json
  src/app/TestFiles/dotnet.json
  src/app/TestFiles/java.json
  src/app/TestFiles/node.json
  src/app/Version.cs
  src/app/WebValidation/IDispose.cs
  src/app/WebValidation/Main.cs
  src/app/WebValidation/Metrics.cs
  src/app/WebValidation/Model/config.cs
  src/app/WebValidation/ReadValidateJson.cs
  src/app/webvalidate.csproj
  src/e2e-tests/TestEndToEnd.cs
  src/e2e-tests/e2e-tests.csproj
  src/unit-tests/TestApp.cs
  src/unit-tests/unit-tests.csproj
Labels: WebV

#51 updated readme
  README.md
  src/app/TestFiles/dotnet.json
  src/app/TestFiles/node.json
  src/app/WebValidation/Model/config.cs
Labels: WebV

#55 update ci to have latest for the utility apps
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.yaml
Labels: Pri1, WebV, size: S

#56 add workflow for issue triage and PR submitted automation
  .github/workflows/open-issues-triage.yml
  .github/workflows/open-pr-submitted.yml
Labels: Pri1, WebV, size: S

#57 Http Status Only Validation for bad.json
  src/app/TestFiles/bad.json
  src/app/TestFiles/badFull.json
Labels: Pri1, WebV, size: S

#59 Changed namespace to CSE.WebValidate
  src/app/Constants.cs
  src/app/GlobalSuppressions.cs
  src/app/Program.cs
  src/app/Validators/ParametersValidator.cs
  src/app/Validators/ResponseValidator.cs
  src/app/Version.cs
  src/app/WebValidation/IDispose.cs
  src/app/WebValidation/Main.cs
  src/app/WebValidation/Metrics.cs
  src/app/WebValidation/Model/JsonArray.cs
  src/app/WebValidation/Model/JsonProperty.cs
  src/app/WebValidation/Model/JsonPropertyByIndex.cs
  src/app/WebValidation/Model/PerfLog.cs
  src/app/WebValidation/Model/PerfTarget.cs
  src/app/WebValidation/Model/Request.cs
  src/app/WebValidation/Model/TimerRequestState.cs
  src/app/WebValidation/Model/Validation.cs
  src/app/WebValidation/Model/ValidationResult.cs
  src/app/WebValidation/Model/config.cs
  src/app/WebValidation/ReadValidateJson.cs
  src/app/webvalidate.csproj
  src/e2e-tests/TestEndToEnd.cs
  src/e2e-tests/e2e-tests.csproj
  src/unit-tests/TestApp.cs
  src/unit-tests/TestArrayValidator.cs
  src/unit-tests/TestCommonValidator.cs
  src/unit-tests/TestObjectValidator.cs
  src/unit-tests/unit-tests.csproj
Labels: WebV

#61 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#60 changed names to bad.json and badJava.json
  src/app/TestFiles/bad.json
  src/app/TestFiles/badFull.json
  src/app/TestFiles/badJava.json
Labels: WebV
